fix

diff --git a/basics_1/0-change_your_home_IP b/basics_1/0-change_your_home_IP
--- a/basics_1/0-change_your_home_IP
+++ b/basics_1/0-change_your_home_IP
@@ -1,19 +1,21 @@
 #!/usr/bin/env bash
-# This script modifies /etc/hosts to change localhost to 127.0.2 and facebook.com to 8.8.8.8
+# Script to configure an Ubuntu server with specific IP addresses
+# - Changes localhost to resolve to 127.0.0.2
+# - Changes facebook.com to resolve to 8.8.8.8
 
-# Check for root
-if [[ "$EUID" -ne 0 ]]; then
-  echo "Please run as root"
-  exit 1
-fi
+# Create a new hosts file
+cp /etc/hosts ~/hosts.new
 
-# Backup /etc/hosts first
-cp /etc/hosts /etc/hosts.bak
+# Update the localhost entry
+sed -i 's/127[.][0-9.]*[[:space:]]localhost$/127.0.0.2 localhost/' ~/hosts.new
+grep -q "127.0.0.2 localhost" ~/hosts.new || echo "127.0.0.2 localhost" >> ~/hosts.new
 
-# Remove any existing localhost or facebook.com entries
-sed -i '/localhost/d' /etc/hosts
-sed -i '/facebook.com/d' /etc/hosts
+# Update the facebook.com entry
+sed -i '/facebook\.com$/d' ~/hosts.new
+echo "8.8.8.8 facebook.com" >> ~/hosts.new
 
-# Add the required entries
-echo "127.0.0.2 localhost" >> /etc/hosts
-echo "8.8.8.8 facebook.com" >> /etc/hosts
+# Replace the original hosts file
+cp -f ~/hosts.new /etc/hosts
+
+# Clean up
+rm -f ~/hosts.new
